Package FotoToons as Flatpak
tchx84/flathub pull request #9
Opened 2020-01-06 19:21 UTC by srevinsaju

WIP, build in progress, unvaidated.

2020-01-06 19:23 UTC, srevinsaju commented on fototoon-port.patch
> ++
Will remove this extra line

2020-01-06 21:01 UTC, tchx84 requested changes
Aside from the comment I left, I noticed 3 issues while testing the app:

1.  The first time you launch the app and load the initial image, the top title bubble is not visible. If you close the app, and then re-open, you will see title bubble. But the weird thing is, if you then type a title and re-open the app, you will get a new title bubble overlapping with the previous one every time. I would bet that this bug is already present in the Sugar version, but would be good to fix it.

2.  Exporting to ogg video is not working, maybe is something silly... like it's actually not writing the file or something like that, because I see no errors or anything.

3.  When you use the "Open" button, it will append the project to the current project. e.g. try opening the same project multiple times and you will understand. We probably need to add/call some cleanup in the read_file method.

Good start!

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        chooser = DesktopSaveChooser(self, filename='untitled.png')
Use `_("Untitled") + '.png'` as we did in other apps.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        self.globes_manager.add_image(self)
No need to pass "self" here, the globes_manager object already has a reference to the activity. When you open the chooser just pass `self._activity`.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        if filename:
Since you are writing a lot of code after this if, it is better to early exit instead of having to re-indent the follow lines.

```
if filename is None:
    return
```

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        chooser = DesktopSaveChooser(self, filename='untitled.ogv')
Same, comment about filename.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        filename = chooser.get_filename()
Add a filter for `.png`.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        output_path = chooser.get_filename()
same comment about adding a filter.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        if output_path:
Same comment about early exiting instead of re-indenting the whole block below.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++            self.add_image(self._activity)
No see to pass self._activity.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++    def add_image(self, parent):
No need for the parent argument.

2020-01-06 21:01 UTC, tchx84 commented on fototoon-port.patch
> ++        chooser = DesktopOpenChooser(parent)
just use self._activity here instead of parent.

2020-01-07 19:40 UTC, srevinsaju commented
@tchx84 with https://github.com/tchx84/flathub/pull/9/commits/05e55ef49a1fce3a05ce22bbb1d0319cc0f85a21 and the other commits below that, the file and pages are removed, but on pressing the `stop_button` , the following segmentation fault happens:
```
(sugarapp:623): GdkPixbuf-CRITICAL **: 22:31:47.832: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
Traceback (most recent call last):
  File "/home/ss/repo/fototoon-activity/historietaactivity.py", line 758, in draw_cb
    self.draw_in_context(context)
  File "/home/ss/repo/fototoon-activity/historietaactivity.py", line 797, in draw_in_context
    self.img_x, self.img_y)
TypeError: Argument 1 does not allow None as a value
SS 0

(sugarapp:623): GdkPixbuf-CRITICAL **: 22:31:57.630: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
Traceback (most recent call last):
  File "/home/ss/repo/fototoon-activity/historietaactivity.py", line 758, in draw_cb
    self.draw_in_context(context)
  File "/home/ss/repo/fototoon-activity/historietaactivity.py", line 797, in draw_in_context
    self.img_x, self.img_y)
TypeError: Argument 1 does not allow None as a value
/usr/lib/python3.7/zipfile.py:1473: UserWarning: Duplicate name: 'image1.png'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
python3: ../../src/cairo.c:524: cairo_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)' failed.
Aborted (core dumped)
```

2020-01-08 14:40 UTC, tchx84 commented
I tested it, and all of the problems I mentioned still persist. I will try to explore these issues myself later this week.

2020-01-31 11:06 UTC, closed without merging